language: node_js

node_js:
  - "10.15.3"

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: build
  on:
    branch: master

notifications:
  - email: false
