/**
 * Redux item actions
 */
export const ITEM = {
  CREATE: {
    SUCCESS: 'ITEM_CREATE_SUCCESS',
    ERROR: 'ITEM_CREATE_ERROR',
  },
  GET: {
    SUCCESS: 'ITEM_GET_SUCCESS',
    ERROR: 'ITEM_GET_ERROR',
  },
  GET_ALL: {
    SUCCESS: 'ITEM_GET_ALL_SUCCESS',
    ERROR: 'ITEM_GET_ALL_ERROR',
  },
  UPDATE: {
    SUCCESS: 'ITEM_UPDATE_SUCCESS',
    ERROR: 'ITEM_UPDATE_ERROR',
  },
  DELETE: {
    SUCCESS: 'ITEM_DELETE_SUCCESS',
    ERROR: 'ITEM_DELETE_ERROR',
  },
};
