/**
 * Redux user actions
 */
export const USER = {
  SIGN_UP: {
    SUCCESS: 'USER_SIGN_UP_SUCCESS',
    ERROR: 'USER_SIGN_UP_ERROR',
    RESET_ERRORS: 'USER_SIGN_UP_RESET_ERRORS',
  },
  UPDATE: {
    SUCCESS: 'USER_UPDATE_SUCCESS',
    ERROR: 'USER_UPDATE_ERROR',
  },
  DELETE: {
    SUCCESS: 'USER_DELETE_SUCCESS',
    ERROR: 'USER_DELETE_ERROR',
  },
  LOGIN: {
    SUCCESS: 'USER_LOGIN_SUCCESS',
    ERROR: 'USER_LOGIN_ERROR',
    RESET_ERRORS: 'USER_LOGIN_RESET_ERRORS',
  },
  LOGOUT: {
    SUCCESS: 'USER_LOGOUT_SUCCESS',
    ERROR: 'USER_LOGOUT_ERROR',
  },
};
