// import { store } from '../store';
/**
 * Redux wishlists actions
 */

export const WISHLIST = {
  CREATE: {
    SUCCESS: 'WISHLIST_CREATE_SUCCESS',
    ERROR: 'WISHLIST_CREATE_ERROR',
  },
  GET: {
    SUCCESS: 'WISHLIST_GET_SUCCESS',
    ERROR: 'WISHLIST_GET_ERROR',
  },
  GET_ALL: {
    SUCCESS: 'WISHLIST_GET_ALL_SUCCESS',
    ERROR: 'WISHLIST_GET_ALL_ERROR',
  },
  UPDATE: {
    SUCCESS: 'WISHLIST_UPDATE_SUCCESS',
    ERROR: 'WISHLIST_UPDATE_ERROR',
  },
  DELETE: {
    SUCCESS: 'WISHLIST_DELETE_SUCCESS',
    ERROR: 'WISHLIST_DELETE_ERROR',
  },
};
